FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends git && \
    apt-get install -y python3 python3-pip unzip && \
    python3 -m pip install --upgrade pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install unsloth

WORKDIR /app
COPY requirements.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.txt