FROM ghcr.io/huggingface/text-generation-inference:latest

RUN apt-get update && apt-get install -y \
    python3-pip \
    unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN python -m ensurepip --upgrade
RUN python -m pip install --no-cache-dir -r requirements.txt